# Generated by Django 5.0.6 on 2024-07-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('receber_noticias', models.BooleanField(default=False)),
            ],
        ),
    ]
